import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/outils/Header";
import PageTransition from "@/components/outils/PageTransition";
import ChangeTransition from "@/components/outils/ChangeTransition";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrainsMono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "700"],
});

export const metadata: Metadata = {
  title: "Aro Lova",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} antialiased`}>
        <Header />
        <ChangeTransition/>
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
